set(PICO_TEST_URL_BASE "https://github.com/kubakos/pico-test/origin/HEAD")
macro(auto_set_url TARGET)
    file(RELATIVE_PATH URL_REL_PATH "${PICO_TEST_PATH}" "${CMAKE_CURRENT_LIST_DIR}")
    pico_set_program_url(${TARGET} "${PICO_TEST_URL_BASE}/${URL_REL_PATH}")
endmacro()
